SELECT
	CEDULA = (SELECT 
				RM1CIDEUDOR FROM RM1E 
				WHERE RM1PRODUCTO+RM1PRESTAMO=RH1PRODUCTO+RH1PRESTAMO
			),
	NOMBRE = (SELECT 
				RTRIM(CM1DCAPEP)+' '+RTRIM(CM1DCAPEM)+' '+RTRIM(CM1DCNOM1)+' '+RTRIM(CM1DCNOM2) 
				FROM CM1D 
				WHERE CM1CEDULA = (SELECT 
									RM1CIDEUDOR FROM RM1E 
									WHERE RM1PRODUCTO+RM1PRESTAMO=RH1PRODUCTO+RH1PRESTAMO)),
	PRODUCTO = RH1PRODUCTO ,
	OPERACION = RH1PRESTAMO ,
	FECHA_PAGO = RH1AFECHAPAGO ,
	DIVIDENDO = RH1ANUMERODIVIDENDO ,
	CAPITAL = RH1ACAPITAL/100 ,
	INTERES = RH1AINTERES/100 ,
	MORA = RH1AMORA/100 ,
	EFECTIVO_PAGADO = RH1AEFECTIVO/100 ,
	CHEQUE_PAGADO = RH1ALOCALES/100 ,
	OBSERVACION = RH1AOBSERVACION

	FROM RH1A
	WHERE RH1AESTATUS = 'C'
		  AND RH1AFECHAPAGO 
			BETWEEN @StartDate and @EndDate
	
	ORDER BY RH1AFECHAPAGO