-- 1) OTORGAMIENTOS DE CREDITO  
IF OBJECT_ID('tempdb..#OPERACIONES') IS NOT NULL DROP TABLE #OPERACIONES   
SELECT 
'OPCREDITO' TIPOTRAN,  
RM1TIDEUDOR TIPODOCU,
RM1CIDEUDOR  DOCUMENTO, 
RM1PRODUCTO , 
RM1PRESTAMO,  
VALOR_E = RM1MONTOPRESTAMO/100 
INTO #OPERACIONES   
FROM RM1E  
WHERE RM1ESTATUS = 'V'
AND RM1FECHACONTABIL BETWEEN @StartDate AND @EndDate

-- 2) ABONOS Y CANCELACIONES
INSERT INTO #OPERACIONES   
SELECT 
'PAGOS' TIPOTRAN,  
(SELECT RM1TIDEUDOR FROM RM1E WHERE RH1PRODUCTO+RH1PRESTAMO = RM1PRODUCTO+RM1PRESTAMO)  TIPODOCU,
(SELECT RM1CIDEUDOR FROM RM1E WHERE RH1PRODUCTO+RH1PRESTAMO = RM1PRODUCTO+RM1PRESTAMO)  DOCUMENTO, 
(SELECT RM1PRODUCTO FROM RM1E WHERE RH1PRODUCTO+RH1PRESTAMO = RM1PRODUCTO+RM1PRESTAMO)  RM1PRODUCTO , 
(SELECT RM1PRESTAMO FROM RM1E WHERE RH1PRODUCTO+RH1PRESTAMO = RM1PRODUCTO+RM1PRESTAMO)  RM1PRESTAMO,  
VALOR_E = RH1ATOTAL/100 
FROM RH1A  
WHERE RH1AFECHAPAGO  BETWEEN @StartDate AND @EndDate   

-- 3) FORMAR LA ESTRUCTURA DESDE LOS TEMPRORALES 
SELECT 
CASE          
 WHEN TIPODOCU = 'E' THEN 'P'          
 ELSE TIPODOCU          
END AS TIPODOCUMENTO,          
DOCUMENTO,          
CLIENTE= (SELECT rtrim(CM1DCAPEP)+ ' ' + rtrim(CM1DCAPEM) + ' ' +  rtrim(CM1DCNOM1) + ' ' + rtrim(CM1DCNOM2) FROM CM1D WHERE CM1CEDULA = DOCUMENTO),          
NACIONALIDAD = 593,
DIRECCION = ISNULL((SELECT TOP 1 CM1LCDIRE FROM CM1L WHERE CM1L.CM1CEDULA = DOCUMENTO AND CM1SECUEN = '1'),''),
PROVINCIA = ISNULL((SELECT TOP 1 CM1LCPROV  FROM CM1L WHERE CM1L.CM1CEDULA = DOCUMENTO AND CM1SECUEN = '1'),''),
CANTON = ISNULL((SELECT TOP 1 CM1LCCANT FROM CM1L WHERE CM1L.CM1CEDULA = DOCUMENTO AND CM1SECUEN = '1'),''),
'CRE',   
PRODUCTO = RM1PRODUCTO,          
CUENTA = RM1PRESTAMO,
CASE 
WHEN TIPOTRAN = 'DEBITOS' THEN  CAST(VALOR_E AS NUMERIC(16,2))          
ELSE CAST(0 AS NUMERIC(16,2))          
END AS VAL_DEB, 
CASE
WHEN TIPOTRAN = 'CREDITOS' THEN  CAST(VALOR_E AS NUMERIC(16,2))          
ELSE CAST(0 AS NUMERIC(16,2))          
END AS VAL_CRE, 
CASE
WHEN TIPOTRAN = 'PAGOS' THEN  CAST(VALOR_E AS NUMERIC(16,2))          
WHEN TIPOTRAN = 'OPCREDITO' THEN  CAST(VALOR_E AS NUMERIC(16,2))          
ELSE CAST(0 AS NUMERIC(16,2))          
END AS VAL_EFE, 
CASE
WHEN TIPOTRAN = 'DEPOSITOS' THEN  CAST(0 AS NUMERIC(16,2))          
ELSE CAST(0 AS NUMERIC(16,2))          
END AS VAL_CHQ,         
VAL_TOTAL = 0,          
'03' TIPO_OPERACION,          
MONEDA = 0,          
'593' PAISTRX ,          
'NA' RAZONSOCIALTRX,          
'NA' IFITRX,          
'NA' NUMPRODTRX          
from #operaciones
 