
-- 1) GENERAR LAS ID DE LAS CUENTAS 
IF OBJECT_ID('tempdb..#MOVCTAS') IS NOT NULL DROP TABLE #MOVCTAS  
SELECT  
CM2DCTIPD TIPODOC,
cm2dccedu DOCUMENTO 
into #MOVCTAS  
FROM CM2    
--select * from cm2 
WHERE 
CM2CUENTA  IN (SELECT DISTINCT(CH3CUENT)  
					FROM CH3 
					WHERE 
							CH3CODIGO  = 'iok'  
							AND CH3FECHA BETWEEN @StartDate and @EndDate--@FECHA_INI AND @FECHA_FIN 
							AND CH3CUENT  <> 0   
							AND CH3TRANS IN ('0700', '1700','1720', '1690','1770', '1600', '1620', '0600'))  
GROUP BY CM2DCTIPD, cm2dccedu 

-- 2) GENERAR LAS CUENTAS QUE TIENEN TRANSACCIONES
IF OBJECT_ID('tempdb..#TOTALCTAS') IS NOT NULL DROP TABLE #TOTALCTAS  
SELECT 
CM2DCTIPD,
cm2dccedu,
CM2CUENTA
INTO #TOTALCTAS  
FROM CM2   
WHERE 
CM2DCCEDU IN (SELECT DOCUMENTO FROM #MOVCTAS)  

--3) SEPARAR LAS TRANSACCIONES DEL HISTORICO 
IF OBJECT_ID('tempdb..#OPERACIONES') IS NOT NULL DROP TABLE #OPERACIONES  
SELECT  
CASE 
WHEN CH3TRANS = '0700' THEN 'DEPOSITOS' 
WHEN CH3TRANS = '1700' THEN 'DEPOSITOS'
WHEN CH3TRANS = '1720' THEN 'DEPOSITOS'
WHEN CH3TRANS = '1600' THEN 'RETIROS'
WHEN CH3TRANS = '1620' THEN 'RETIROS'
WHEN CH3TRANS = '0600' THEN 'RETIROS' 
WHEN CH3TRANS = '1770' THEN 'CREDITOS'
WHEN CH3TRANS = '1690' THEN 'DEBITOS'
END AS TIPOTRAN,  
CM2DCTIPD TIPODOCU,
cm2dccedu DOCUMENTO, 
CH3PRODUC, CH3CUENT ,  
VALOR = convert(numeric(16),SUBSTRING(CH3VARIAB,1,16))/100 
INTO #OPERACIONES   
FROM CH3 , #TOTALCTAS  
WHERE  
	cm2cuenta  = CH3CUENT   
AND CH3CODIGO   = 'iok'  
AND CH3FECHA  BETWEEN @StartDate and @EndDAte --@FECHA_INI AND @FECHA_FIN 
AND CH3CUENT  <> 0  
AND CH3TRANS IN ('0700', '1700','1720', '1690','1770', '1600', '1620', '0600') 
--GROUP BY CM2DCTIPD, CM2DCCEDU, CH3PRODUC, CH3CUENT   

IF OBJECT_ID('tempdb..#OPERACIONESR') IS NOT NULL DROP TABLE #OPERACIONESR   
SELECT 
TIPOTRAN,TIPODOCU,DOCUMENTO, CH3PRODUC, CH3CUENT, VALOR_E=SUM(VALOR) 
INTO #OPERACIONESR
FROM #OPERACIONES
GROUP BY TIPOTRAN,TIPODOCU,DOCUMENTO, CH3PRODUC, CH3CUENT
--SELECT * FROM #OPERACIONESR 

-- 4) FORMAR LA ESTRUCTURA DESDE LOS TEMPRORALES 
SELECT 
CASE          
 WHEN TIPODOCU = 'E' THEN 'P'          
 ELSE TIPODOCU          
END AS TIPODOCUMENTO,          
DOCUMENTO,          --SELECT * FROM CM1D 
CLIENTE= (SELECT rtrim(CM1DCAPEP)+ ' ' + rtrim(CM1DCAPEM) + ' ' +  rtrim(CM1DCNOM1) + ' ' + rtrim(CM1DCNOM2) FROM CM1D WHERE CM1CEDULA = DOCUMENTO),          
NACIONALIDAD = 593,
DIRECCION = ISNULL((SELECT TOP 1 CM1LCDIRE FROM CM1L WHERE CM1L.CM1CEDULA = DOCUMENTO AND CM1SECUEN = '1'),''),
PROVINCIA = ISNULL((SELECT TOP 1 CM1LCPROV  FROM CM1L WHERE CM1L.CM1CEDULA = DOCUMENTO AND CM1SECUEN = '1'),''),
CANTON = ISNULL((SELECT TOP 1 CM1LCCANT FROM CM1L WHERE CM1L.CM1CEDULA = DOCUMENTO AND CM1SECUEN = '1'),''),
'AHO',
PRODUCTO = CH3PRODUC,          
CUENTA = CH3CUENT,
CASE 
WHEN TIPOTRAN = 'DEBITOS' THEN  CAST(VALOR_E AS NUMERIC(16,2))          
ELSE CAST(0 AS NUMERIC(16,2))          
END AS VAL_DEB, 
CASE
WHEN TIPOTRAN = 'CREDITOS' THEN  CAST(VALOR_E AS NUMERIC(16,2))          
ELSE CAST(0 AS NUMERIC(16,2))          
END AS VAL_CRE, 
CASE
WHEN TIPOTRAN = 'DEPOSITOS' THEN  CAST(VALOR_E AS NUMERIC(16,2))          
WHEN TIPOTRAN = 'RETIROS' THEN  CAST(VALOR_E AS NUMERIC(16,2))          
ELSE CAST(0 AS NUMERIC(16,2))          
END AS VAL_EFE, 
CASE
WHEN TIPOTRAN = 'DEPOSITOS' THEN  CAST(0 AS NUMERIC(16,2))          
ELSE CAST(0 AS NUMERIC(16,2))          
END AS VAL_CHQ,         
VAL_TOTAL = 0,          
'03' TIPO_OPERACION,          
MONEDA = 0,          
'593' PAISTRX ,          
'NA' RAZONSOCIALTRX,          
'NA' IFITRX,          
'NA' NUMPRODTRX          
from #operacionesR
 